name: Python Package using Conda

on:
  - push

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: fo,tre,brite,Te,Nd,abd
          skip: "./tests/file/*,./kegg_manual/data/brite/*,./kegg_manual/data/compound/*,./kegg_manual/data/ec/*,./kegg_manual/data/ko/*,./kegg_manual/data/manual/*,./kegg_manual/data/module/*,./kegg_manual/data/organism"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Install checks
        run: |
          conda install black pytest --name base --solver classic
      - name: Lint with black
        run: |
          black --check --diff .
      - name: Test with pytest
        run: |
          python -m pytest -vv
